### PR TITLE
Fix atom colon location

### PR DESCRIPTION
**Pull request by cvortmann**
The context has a `:conn` key not a `conn:` key.

### CODE REVIEW

**Comment by cvortmann** [comment]
@Gazler this is another _Guides_ PR 😄

**Comment by Gazler** [comment]
I think you opened these PRs against the wrong repository!

**Comment by cvortmann** [comment]
Is there a separate project for the guides?

**Comment by cvortmann** [comment]
@Gazler ah 🤦‍♂️ 😄

**Pull request closed without merging**
